package jg;

import com.max.xiaoheihe.router.interceptors.MessageAndFriendsInterceptor;
import com.max.xiaoheihe.router.interceptors.PostPathInterceptor;
import com.max.xiaoheihe.router.interceptors.f;
import com.max.xiaoheihe.router.interceptors.g;
import com.max.xiaoheihe.router.interceptors.i;
import com.max.xiaoheihe.router.interceptors.j;
import com.max.xiaoheihe.router.interceptors.k;
import com.max.xiaoheihe.router.interceptors.l;
import com.max.xiaoheihe.router.interceptors.n;
import com.max.xiaoheihe.router.interceptors.p;
import com.max.xiaoheihe.router.interceptors.q;
import com.sankuai.waimai.router.common.h;
import com.sankuai.waimai.router.common.o;

/* JADX INFO: compiled from: UriAnnotationInit_71852a8698faea9178ef86c274234b3c.java */
/* JADX INFO: loaded from: classes8.dex */
public class c implements h {
    @Override // com.sankuai.waimai.router.common.h, com.sankuai.waimai.router.components.b
    /* JADX INFO: renamed from: d */
    public void a(o oVar) {
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.J4, "com.max.xiaoheihe.module.chat.MsgConversationActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.S4, "com.max.xiaoheihe.module.chat.MsgConversationActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.X4, "com.max.xiaoheihe.module.chat.StrangerMsgSettingActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.T4, "com.max.xiaoheihe.module.chat.IMFriendSettingActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131251s4, "com.max.xiaoheihe.module.webview.WebActionActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131143d1, "com.max.xiaoheihe.module.game.WriteGameCommentActivity", false, new q());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.Y2, "com.max.xiaoheihe.module.game.WriteGameCommentActivity", false, new q());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131186j2, "com.max.xiaoheihe.module.game.GameWishListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.N2, "com.max.xiaoheihe.module.game.GameDeveloperListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131270v2, "com.max.xiaoheihe.module.game.GameParticularTagListActivity", false, new f());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131173h3, "com.max.xiaoheihe.module.game.GameAddTagsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131152e3, "com.max.xiaoheihe.module.game.GameMorelikeActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131144d2, "com.max.xiaoheihe.module.game.GameStoreOrderDetailActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.V1, "com.max.xiaoheihe.module.game.GameStoreActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.M2, "com.max.xiaoheihe.module.game.GamesOfUnreleasedActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.J3, "com.max.xiaoheihe.module.game.pubg.PUBGPlayerOverViewActivity", false, new com.max.xiaoheihe.module.game.pubg.f());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.O2, "com.max.xiaoheihe.module.game.GameCompilationActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131150e1, "com.max.xiaoheihe.module.game.WriteGameCommentImpressionsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131284x2, "com.max.xiaoheihe.module.game.GameRecommendedListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131145d3, "com.max.xiaoheihe.module.game.GameBundlesActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.B2, "com.max.xiaoheihe.module.game.GetGameActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.U2, "com.max.xiaoheihe.module.game.GetGameActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.W1, "com.max.xiaoheihe.module.mall.MallOrderListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.X1, "com.max.xiaoheihe.module.mall.MallOrderDetailActivity", false, new i());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.G1, "com.max.xiaoheihe.module.account.UserAchievementActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131202l4, "com.max.xiaoheihe.module.account.GameAccountActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131223o4, "com.max.xiaoheihe.module.account.UpdateAccountActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131153e4, "com.max.xiaoheihe.module.account.SettingActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131225p, "com.max.xiaoheihe.module.account.SetSubscribedTagsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.U1, "com.max.xiaoheihe.module.account.MeHomeActivity", false, new j());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131209m4, "com.max.xiaoheihe.module.account.AccountManagerActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131237q4, "com.max.xiaoheihe.module.account.VerifyPhoneActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131283x1, "com.max.xiaoheihe.module.account.FollowingAndFansActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131174h4, "com.max.xiaoheihe.module.account.PrivacySettingsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131195k4, "com.max.xiaoheihe.module.account.FeedbackActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131230p4, "com.max.xiaoheihe.module.account.InviteCodeActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131167g4, "com.max.xiaoheihe.module.account.GeneralSettingsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131192k1, "com.max.xiaoheihe.module.bbs.HashtagDetailActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131227p1, "com.max.xiaoheihe.module.bbs.HashtagDetailActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131171h1, "com.max.xiaoheihe.module.bbs.ChannelListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131286x4, "com.max.xiaoheihe.module.bbs.UserNotifyListActivity", false, new p());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.E4, "com.max.xiaoheihe.module.bbs.UserNotifyListActivity", false, new p());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.H4, "com.max.xiaoheihe.module.bbs.UserNotifyListActivity", false, new p());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131188j4, "com.max.xiaoheihe.module.bbs.UserRelationsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.Q1, "com.max.xiaoheihe.module.bbs.DraftListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131136c1, "com.max.xiaoheihe.module.bbs.post_edit.PictureVideoEditPostActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.X2, "com.max.xiaoheihe.module.bbs.ChannelsDetailActivity", false, new com.max.xiaoheihe.router.interceptors.b());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131164g1, "com.max.xiaoheihe.module.bbs.ChannelsDetailActivity", false, new com.max.xiaoheihe.router.interceptors.b());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.Z2, "com.max.xiaoheihe.module.bbs.ChannelsDetailActivity", false, new com.max.xiaoheihe.router.interceptors.b());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131204m, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/home/moment", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/home/recommend", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/home/rank", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131246s, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.J, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/bbs/recommend", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.M, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/bbs/list", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/bbs/list_v2", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/bbs/waterfall", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/bbs/web_writebox", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131235q2, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/game/recommend", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/game/recommend_v2", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/game/rank", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/game/comment_recommend", "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131262u1, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131269v1, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.K1, "com.max.xiaoheihe.MainActivity", false, new g());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.V2, "com.max.xiaoheihe.module.trade.ItemTradeCenterActivity", false, new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.N5, "com.max.xiaoheihe.module.webview.InjectJsV2Activity", false, new com.max.xiaoheihe.router.interceptors.h());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.W4, "com.max.xiaoheihe.module.game.GameDiscountListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131293y4, "com.max.xiaoheihe.module.game.GameDiscountListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.D3, "com.max.xiaoheihe.module.game.SteamGameShotActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.H3, "com.max.xiaoheihe.module.game.xbox.XboxAchievementRankActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.P2, "com.max.xiaoheihe.module.game.H5GameCenterActivity", false, new com.max.xiaoheihe.router.interceptors.e(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.B3, "com.max.xiaoheihe.module.game.nswitch.SwitchDetailActivity", false, new com.max.xiaoheihe.router.interceptors.o());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.D2, "com.max.xiaoheihe.module.game.RecommendBoardActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.F1, "com.max.xiaoheihe.module.favour.FavourAndHistoryActivity", false, new com.max.xiaoheihe.router.interceptors.c());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131290y1, "com.max.xiaoheihe.module.favour.FavourAndHistoryActivity", false, new com.max.xiaoheihe.router.interceptors.c());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.I1, "com.max.xiaoheihe.module.favour.CYPageActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131120a, "com.max.xiaoheihe.module.mall.FetchSignInCookiesActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.P4, "com.max.xiaoheihe.module.account.SendToFriendActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131279w4, "com.max.xiaoheihe.module.account.MessageAndFriendsActivity", false, new MessageAndFriendsInterceptor());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131276w1, "com.max.xiaoheihe.module.account.MessageAndFriendsActivity", false, new MessageAndFriendsInterceptor());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.I3, "com.max.xiaoheihe.module.account.PlatformFriendsActivity", false, new n());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.F3, "com.max.xiaoheihe.module.account.SetAPIKeyV2Activity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.E, "com.max.xiaoheihe.module.account.specificsearch.UserCenteredSearchActivity", false, new com.max.xiaoheihe.module.account.specificsearch.c());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.F, "com.max.xiaoheihe.module.account.specificsearch.UserCenteredSearchActivity", false, new com.max.xiaoheihe.module.account.specificsearch.c());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.G, "com.max.xiaoheihe.module.account.specificsearch.UserCenteredSearchActivity", false, new com.max.xiaoheihe.module.account.specificsearch.c());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.H, "com.max.xiaoheihe.module.account.specificsearch.UserCenteredSearchActivity", false, new com.max.xiaoheihe.module.account.specificsearch.c());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131160f4, "com.max.xiaoheihe.module.account.SetPushStateActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131181i4, "com.max.xiaoheihe.module.account.DebugSettingActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131156f0, "com.max.xiaoheihe.module.bbs.post.ui.activitys.PicturePostPageActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.S, "com.max.xiaoheihe.module.bbs.post.ui.activitys.NormalPostPageActivity", false, new com.max.xiaoheihe.router.interceptors.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131128b0, "com.max.xiaoheihe.module.bbs.post.ui.activitys.NormalPostPageActivity", false, new com.max.xiaoheihe.router.interceptors.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131142d0, "com.max.xiaoheihe.module.bbs.post.ui.activitys.WebNewsPostPageActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131149e0, "com.max.xiaoheihe.module.bbs.post.ui.activitys.ConceptPostPageActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131135c0, "com.max.xiaoheihe.module.bbs.post.ui.activitys.WikiPostPageActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.B4, "com.max.xiaoheihe.module.bbs.messagecenter.AllCommentsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.R4, "com.max.xiaoheihe.module.bbs.messagecenter.MessageCenterActivity", false, new k());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131300z4, "com.max.xiaoheihe.module.bbs.messagecenter.MessageCenterActivity", false, new k());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.A4, "com.max.xiaoheihe.module.bbs.messagecenter.MessageCenterActivity", false, new k());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.C4, "com.max.xiaoheihe.module.bbs.messagecenter.MessageCenterActivity", false, new k());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.D4, "com.max.xiaoheihe.module.bbs.messagecenter.MessageCenterActivity", false, new k());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.G4, "com.max.xiaoheihe.module.bbs.messagecenter.MessageCenterActivity", false, new k());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131199l1, "com.max.xiaoheihe.module.bbs.HotNewsStyleActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131239r, "com.max.xiaoheihe.module.bbs.HotNewsActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.A0, "com.max.xiaoheihe.module.bbs.post_edit.NewLinkEditActivity", false, new PostPathInterceptor());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131129b1, "com.max.xiaoheihe.module.bbs.post_edit.NewLinkEditActivity", false, new PostPathInterceptor());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131157f1, "com.max.xiaoheihe.module.bbs.post_edit.PostTabActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131234q1, "com.max.xiaoheihe.module.bbs.TemplateHashtagListActivity", false, new com.sankuai.waimai.router.core.h[0]);
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.R3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.T3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.U3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.X3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131132b4, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.Z3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.V3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.W3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.Y3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131125a4, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.K3, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/game/pubg/detail_container_v2", "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131216n4, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.F2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.G2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.I2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.H2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.L2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.J2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.K2, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, com.max.xiaoheihe.module.littleprogram.b.f88755p, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131139c4, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131248s1, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131255t1, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131189j5, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, "/flutter/heybox_voice", "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.B5, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131231p5, "com.max.xiaoheihe.module.littleprogram.MiniProgramContainerActivity", false, new l(), new yc.a());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131172h2, "com.max.xiaoheihe.base.FragmentContainerActivity", false, new com.max.xiaoheihe.router.interceptors.d());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.Y1, "com.max.xiaoheihe.base.FragmentContainerActivity", false, new com.max.xiaoheihe.router.interceptors.d());
        oVar.k(hg.b.f119169a, hg.b.f119170b, lb.d.f131137c2, "com.max.xiaoheihe.base.FragmentContainerActivity", false, new com.max.xiaoheihe.router.interceptors.d());
    }
}
