package cj;

import android.os.Parcel;
import kotlin.NotImplementedError;

/* JADX INFO: compiled from: Parceler.kt */
/* JADX INFO: loaded from: classes5.dex */
public interface c<T> {

    /* JADX INFO: compiled from: Parceler.kt */
    public static final class a {
        @dl.d
        public static <T> T[] a(@dl.d c<T> cVar, int i10) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    T a(@dl.d Parcel parcel);

    void b(T t10, @dl.d Parcel parcel, int i10);

    @dl.d
    T[] newArray(int i10);
}
